mandatoryAccounts:
  # We recommend you do not change mandatory account names. These are used within Landing Zone Accelerator to reference the accounts from other config files.
  # The "name" value does not currently support spaces
  # The "name" value DOES NOT need to match the account name
  - name: Management
    description: The management (primary) account. Do not change the name field for this mandatory account. Note, the account name key does not need to match the AWS account name.
    email: suportebaixaaws@prodam.sp.gov.br
    organizationalUnit: Root
  - name: LogArchive
    description: The log archive account. Do not change the name field for this mandatory account. Note, the account name key does not need to match the AWS account name.
    email: suportebaixaaws+logarchive@prodam.sp.gov.br
    organizationalUnit: Security
  - name: Audit
    description: The security audit account (also referred to as the audit account). Do not change the name field for this mandatory account. Note, the account name key does not need to match the AWS account name.
    email: suportebaixaaws+audit@prodam.sp.gov.br
    organizationalUnit: Security
workloadAccounts:
  - name: LZA-External
    description: >- 
       This account handles all configurations related to the LZA structure.
    email: suportebaixaaws+lza@prodam.sp.gov.br
    organizationalUnit: Infrastructure
    warm: false
  - name: Network
    description: >- 
       This account handles all configurations related to the Network structure.
    email: suportebaixaaws+network@prodam.sp.gov.br
    organizationalUnit: Infrastructure
    warm: false
  - name: SharedServices
    description: >- 
       This account handles all configurations related to the Network structure.
    email: suportebaixaaws+sharedservices@prodam.sp.gov.br
    organizationalUnit: Infrastructure
    warm: false
